/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kercer_kerdb_jnibridge_DB */

#ifndef _Included_com_kercer_kerdb_jnibridge_DB
#define _Included_com_kercer_kerdb_jnibridge_DB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativePut
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativePut
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeGet
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeGet__JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeGet
 * Signature: (JJLjava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeGet__JJLjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeDelete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeDelete
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeWrite
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeWrite
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeDestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeDestroy
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeIterator
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeIterator
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeGetSnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeGetSnapshot
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    nativeReleaseSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_kercer_kerdb_jnibridge_DB_nativeReleaseSnapshot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_kercer_kerdb_jnibridge_DB
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kercer_kerdb_jnibridge_DB_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
